language: java
jdk:
 - oraclejdk8
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
script:
 mvn verify
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
- bash <(curl -s https://codecov.io/bash)